### ISSUE TITLE
Example for annotations file and priority file (annotations_to_dir)

### ISSUE THREAD

**Issue by dmurphree** [ncsa/DigiPath_MLTK#44]
What should the annotations file and priority file look like for the "annotations_to_dir" functionality?

I have Aperio SVS files and the .xml files produced from annotating via Image Scope.  I would like to take the annotated regions and write them to a directory.

Thank you!

**Comment by dlanier** [comment]
The annotation file must follow the QuPath Annotation convention: https://qupath.github.io/



DANIEL LANIER
RES PRGRMR

University of Illinois at Urbana-Champaign
Vice Chancellor Research Institutes
National Center for Supercomputing Applications (NCSA)
RM 3103
1205 Clark St | M/C 251
Urbana
2179790959 | lanier4@illinois.edu<mailto:lanier4@illinois.edu>
www.ncsa.illinois.edu<http://www.ncsa.illinois.edu/>

[https://webtools.illinois.edu/webservices/js/ds/signature_logo.png]<http://illinois.edu/>

Under the Illinois Freedom of Information Act any written communication to or from university employees regarding university business is a public record and may be subject to public disclosure.
________________________________

**Comment by dmurphree** [comment]
Thanks Daniel!  What about the priority file?

**Comment by dlanier** [comment]
The priorities are defined in the .xml file produced by QuPath.

**Comment by dmurphree** [comment]
Thank you!
